#!/bin/sh

if [ ! -e $HOME/.vim/bundle/vundle ]; then
  git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle
fi
vim -u $HOME/.vimrc.bundles +BundleInstall +qa

if [ ! -e $HOME/.zsh/antigen ]; then
  git clone https://github.com/zsh-users/antigen.git $HOME/.zsh/antigen
fi
